### ISSUE TITLE
傻逼玩意

### ISSUE THREAD

**Issue by ghost** [cobain200/cobain200.github.io#1]

**Comment by cobain200** [comment]
真有出息呀你




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cobain200/cobain200.github.io"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月14日(星期天) 晚上8:02
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[cobain200/cobain200.github.io] 傻逼玩意 (Issue #1)





 
什么一击脱离的臭傻逼，快点滚出来merge你妈的pr。
 玩网烂蛆nmsl。
 快点找你的好朋友诉苦去吧，瘪三东西。
 廉价hook，脑瘫玩意。
 无间道刘桑。
 早点重开吧。
